#!/usr/bin/env bash
# Generates the dev launcher at ~/bin/cercano from cercano-launcher.sh, with
# THIS clone's repo path baked in as the default (CERCANO_REPO still
# overrides at runtime). Safe to re-run; refuses to clobber a file it did
# not generate unless --force is given.
#
# Usage: scripts/install-launcher.sh [--force]     (or: make launcher)
set -euo pipefail

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
TEMPLATE="$SCRIPT_DIR/cercano-launcher.sh"
DEST_DIR="$HOME/bin"
DEST="$DEST_DIR/cercano"
MARKER="# generated by install-launcher.sh"

[[ -f "$TEMPLATE" ]] || { echo "install-launcher: template not found: $TEMPLATE" >&2; exit 1; }
if [[ ! -d "$REPO_ROOT/source/server/cmd/cercano" || ! -f "$REPO_ROOT/source/clients/cli/main.go" ]]; then
    echo "install-launcher: $REPO_ROOT does not look like the Cercano repo root" >&2
    exit 1
fi

if [[ -e "$DEST" && $FORCE -eq 0 ]] && ! grep -qF "$MARKER" "$DEST"; then
    echo "install-launcher: $DEST exists and was not generated by this script — rerun with --force to overwrite" >&2
    exit 1
fi

mkdir -p "$DEST_DIR"
# Emit: shebang, marker, then the template body with the REPO default
# rewritten to this clone. The launcher script stays the single source of
# truth; only the default path is substituted.
{
    head -n 1 "$TEMPLATE"
    echo "$MARKER"
    tail -n +2 "$TEMPLATE" | sed "s|^REPO=.*|REPO=\"\${CERCANO_REPO:-$REPO_ROOT}\"|"
} > "$DEST"
chmod +x "$DEST"
echo "installed $DEST (repo: $REPO_ROOT)"

case ":$PATH:" in
    *":$DEST_DIR:"*) ;;
    *) echo "warning: $DEST_DIR is not on your PATH" >&2 ;;
esac
