#!/usr/bin/env bash
# Test for install-launcher.sh. Runs the generator against a temp HOME and
# asserts the emitted launcher. Invoke directly: scripts/install-launcher_test.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
TMP_HOME="$(mktemp -d)"
trap 'rm -rf "$TMP_HOME"' EXIT

fail() { echo "FAIL: $1" >&2; exit 1; }

# 1. Fresh install bakes the repo path, marker, export line, and exec bit.
HOME="$TMP_HOME" "$SCRIPT_DIR/install-launcher.sh" >/dev/null
DEST="$TMP_HOME/bin/cercano"
[[ -x "$DEST" ]] || fail "no executable at $DEST"
grep -qF "# generated by install-launcher.sh" "$DEST" || fail "marker line missing"
grep -qF "REPO=\"\${CERCANO_REPO:-$REPO_ROOT}\"" "$DEST" || fail "repo path not baked into REPO default"
grep -qF 'export CERCANO_REPO="$REPO"' "$DEST" || fail "export CERCANO_REPO line missing"

# 2. Refuses to overwrite a file it did not generate.
echo "#!/bin/sh" > "$DEST"
if HOME="$TMP_HOME" "$SCRIPT_DIR/install-launcher.sh" >/dev/null 2>&1; then
    fail "overwrote a non-generated file without --force"
fi

# 3. --force overwrites anything.
HOME="$TMP_HOME" "$SCRIPT_DIR/install-launcher.sh" --force >/dev/null
grep -qF "# generated by install-launcher.sh" "$DEST" || fail "--force did not regenerate"

# 4. Re-running over its own output succeeds without --force (marker present).
HOME="$TMP_HOME" "$SCRIPT_DIR/install-launcher.sh" >/dev/null || fail "re-run over own output failed"

echo "PASS"
