// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible actions for a FileChange.
type FileAction int32

const (
	FileAction_CREATE FileAction = 0
	FileAction_UPDATE FileAction = 1
	FileAction_DELETE FileAction = 2
)

// Enum value maps for FileAction.
var (
	FileAction_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	FileAction_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x FileAction) Enum() *FileAction {
	p := new(FileAction)
	*p = x
	return p
}

func (x FileAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileAction) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (FileAction) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x FileAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileAction.Descriptor instead.
func (FileAction) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// Incremental token from LLM streaming.
type TokenDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDelta) Reset() {
	*x = TokenDelta{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDelta) ProtoMessage() {}

func (x *TokenDelta) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDelta.ProtoReflect.Descriptor instead.
func (*TokenDelta) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TokenDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// The response message for StreamProcessRequest.
type StreamProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamProcessResponse_Progress
	//	*StreamProcessResponse_FinalResponse
	//	*StreamProcessResponse_TokenDelta
	Payload       isStreamProcessResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessResponse) Reset() {
	*x = StreamProcessResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessResponse) ProtoMessage() {}

func (x *StreamProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessResponse.ProtoReflect.Descriptor instead.
func (*StreamProcessResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StreamProcessResponse) GetPayload() isStreamProcessResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamProcessResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*StreamProcessResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *StreamProcessResponse) GetFinalResponse() *ProcessRequestResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamProcessResponse_FinalResponse); ok {
			return x.FinalResponse
		}
	}
	return nil
}

func (x *StreamProcessResponse) GetTokenDelta() *TokenDelta {
	if x != nil {
		if x, ok := x.Payload.(*StreamProcessResponse_TokenDelta); ok {
			return x.TokenDelta
		}
	}
	return nil
}

type isStreamProcessResponse_Payload interface {
	isStreamProcessResponse_Payload()
}

type StreamProcessResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type StreamProcessResponse_FinalResponse struct {
	FinalResponse *ProcessRequestResponse `protobuf:"bytes,2,opt,name=final_response,json=finalResponse,proto3,oneof"`
}

type StreamProcessResponse_TokenDelta struct {
	TokenDelta *TokenDelta `protobuf:"bytes,3,opt,name=token_delta,json=tokenDelta,proto3,oneof"`
}

func (*StreamProcessResponse_Progress) isStreamProcessResponse_Payload() {}

func (*StreamProcessResponse_FinalResponse) isStreamProcessResponse_Payload() {}

func (*StreamProcessResponse_TokenDelta) isStreamProcessResponse_Payload() {}

// Progress update during a long-running task.
type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message for ProcessRequest.
type ProcessRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Input string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // User input or query
	// Field 2 removed (was CloudProviderConfig provider_config)
	WorkDir        string `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`                      // Optional working directory for agentic tasks
	FileName       string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                   // Optional filename for agentic tasks
	ConversationId string `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Optional conversation ID for multi-turn history
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessRequestRequest) Reset() {
	*x = ProcessRequestRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestRequest) ProtoMessage() {}

func (x *ProcessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequestRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequestRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessRequestRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ProcessRequestRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ProcessRequestRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ProcessRequestRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Runtime configuration update request.
type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalModel    string                 `protobuf:"bytes,1,opt,name=local_model,json=localModel,proto3" json:"local_model,omitempty"`          // Ollama model name (e.g., "qwen3-coder", "GLM-4.7-Flash")
	CloudProvider string                 `protobuf:"bytes,2,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"` // Cloud provider name (e.g., "google", "anthropic")
	CloudModel    string                 `protobuf:"bytes,3,opt,name=cloud_model,json=cloudModel,proto3" json:"cloud_model,omitempty"`          // Cloud model name (e.g., "gemini-1.5-flash", "claude-3-opus")
	CloudApiKey   string                 `protobuf:"bytes,4,opt,name=cloud_api_key,json=cloudApiKey,proto3" json:"cloud_api_key,omitempty"`     // API key for the cloud provider
	OllamaUrl     string                 `protobuf:"bytes,5,opt,name=ollama_url,json=ollamaUrl,proto3" json:"ollama_url,omitempty"`             // Ollama endpoint URL (e.g., "http://mac-studio.local:11434")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConfigRequest) GetLocalModel() string {
	if x != nil {
		return x.LocalModel
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudModel() string {
	if x != nil {
		return x.CloudModel
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudApiKey() string {
	if x != nil {
		return x.CloudApiKey
	}
	return ""
}

func (x *UpdateConfigRequest) GetOllamaUrl() string {
	if x != nil {
		return x.OllamaUrl
	}
	return ""
}

// Runtime configuration update response.
type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message for ProcessRequest.
type ProcessRequestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Output           string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                                             // AI generated output
	FileChanges      []*FileChange          `protobuf:"bytes,2,rep,name=file_changes,json=fileChanges,proto3" json:"file_changes,omitempty"`                // Optional structured file modifications
	RoutingMetadata  *RoutingMetadata       `protobuf:"bytes,3,opt,name=routing_metadata,json=routingMetadata,proto3" json:"routing_metadata,omitempty"`    // Optional metadata about the model/routing
	ValidationErrors string                 `protobuf:"bytes,4,opt,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"` // Optional captured validation errors (e.g. test failures)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessRequestResponse) Reset() {
	*x = ProcessRequestResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestResponse) ProtoMessage() {}

func (x *ProcessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequestResponse.ProtoReflect.Descriptor instead.
func (*ProcessRequestResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessRequestResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ProcessRequestResponse) GetFileChanges() []*FileChange {
	if x != nil {
		return x.FileChanges
	}
	return nil
}

func (x *ProcessRequestResponse) GetRoutingMetadata() *RoutingMetadata {
	if x != nil {
		return x.RoutingMetadata
	}
	return nil
}

func (x *ProcessRequestResponse) GetValidationErrors() string {
	if x != nil {
		return x.ValidationErrors
	}
	return ""
}

// Represents a change to a specific file.
type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                            // File path (relative to work_dir)
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // New file content
	Action        FileAction             `protobuf:"varint,3,opt,name=action,proto3,enum=agent.FileAction" json:"action,omitempty"` // Type of action to perform
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FileChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChange) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileChange) GetAction() FileAction {
	if x != nil {
		return x.Action
	}
	return FileAction_CREATE
}

// Metadata about the routing and model execution.
type RoutingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`     // Name of the model that processed the request
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                  // Confidence score for the routing decision
	Escalated     bool                   `protobuf:"varint,3,opt,name=escalated,proto3" json:"escalated,omitempty"`                     // Whether the request was escalated to cloud
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                        // Active Ollama endpoint URL that served the request
	IsFallback    bool                   `protobuf:"varint,5,opt,name=is_fallback,json=isFallback,proto3" json:"is_fallback,omitempty"` // Whether the fallback (local) endpoint was used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingMetadata) Reset() {
	*x = RoutingMetadata{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingMetadata) ProtoMessage() {}

func (x *RoutingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingMetadata.ProtoReflect.Descriptor instead.
func (*RoutingMetadata) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RoutingMetadata) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RoutingMetadata) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RoutingMetadata) GetEscalated() bool {
	if x != nil {
		return x.Escalated
	}
	return false
}

func (x *RoutingMetadata) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RoutingMetadata) GetIsFallback() bool {
	if x != nil {
		return x.IsFallback
	}
	return false
}

// Request to list available models on the active Ollama instance.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

// A single model available on an Ollama instance.
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Model name (e.g., "qwen3-coder:latest")
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                              // Model size in bytes
	ModifiedAt    string                 `protobuf:"bytes,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"` // Last modified timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ModelInfo) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

// Response containing available models.
type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"&\n" +
	"\n" +
	"TokenDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xd5\x01\n" +
	"\x15StreamProcessResponse\x123\n" +
	"\bprogress\x18\x01 \x01(\v2\x15.agent.ProgressUpdateH\x00R\bprogress\x12F\n" +
	"\x0efinal_response\x18\x02 \x01(\v2\x1d.agent.ProcessRequestResponseH\x00R\rfinalResponse\x124\n" +
	"\vtoken_delta\x18\x03 \x01(\v2\x11.agent.TokenDeltaH\x00R\n" +
	"tokenDeltaB\t\n" +
	"\apayload\"*\n" +
	"\x0eProgressUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x15ProcessRequestRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\"\xc1\x01\n" +
	"\x13UpdateConfigRequest\x12\x1f\n" +
	"\vlocal_model\x18\x01 \x01(\tR\n" +
	"localModel\x12%\n" +
	"\x0ecloud_provider\x18\x02 \x01(\tR\rcloudProvider\x12\x1f\n" +
	"\vcloud_model\x18\x03 \x01(\tR\n" +
	"cloudModel\x12\"\n" +
	"\rcloud_api_key\x18\x04 \x01(\tR\vcloudApiKey\x12\x1d\n" +
	"\n" +
	"ollama_url\x18\x05 \x01(\tR\tollamaUrl\"J\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd6\x01\n" +
	"\x16ProcessRequestResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x124\n" +
	"\ffile_changes\x18\x02 \x03(\v2\x11.agent.FileChangeR\vfileChanges\x12A\n" +
	"\x10routing_metadata\x18\x03 \x01(\v2\x16.agent.RoutingMetadataR\x0froutingMetadata\x12+\n" +
	"\x11validation_errors\x18\x04 \x01(\tR\x10validationErrors\"e\n" +
	"\n" +
	"FileChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12)\n" +
	"\x06action\x18\x03 \x01(\x0e2\x11.agent.FileActionR\x06action\"\xab\x01\n" +
	"\x0fRoutingMetadata\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\tescalated\x18\x03 \x01(\bR\tescalated\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vis_fallback\x18\x05 \x01(\bR\n" +
	"isFallback\"\x13\n" +
	"\x11ListModelsRequest\"T\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x03 \x01(\tR\n" +
	"modifiedAt\">\n" +
	"\x12ListModelsResponse\x12(\n" +
	"\x06models\x18\x01 \x03(\v2\x10.agent.ModelInfoR\x06models*0\n" +
	"\n" +
	"FileAction\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\xc0\x02\n" +
	"\x05Agent\x12O\n" +
	"\x0eProcessRequest\x12\x1c.agent.ProcessRequestRequest\x1a\x1d.agent.ProcessRequestResponse\"\x00\x12V\n" +
	"\x14StreamProcessRequest\x12\x1c.agent.ProcessRequestRequest\x1a\x1c.agent.StreamProcessResponse\"\x000\x01\x12I\n" +
	"\fUpdateConfig\x12\x1a.agent.UpdateConfigRequest\x1a\x1b.agent.UpdateConfigResponse\"\x00\x12C\n" +
	"\n" +
	"ListModels\x12\x18.agent.ListModelsRequest\x1a\x19.agent.ListModelsResponse\"\x00B!Z\x1fcercano/source/server/pkg/protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(FileAction)(0),                // 0: agent.FileAction
	(*TokenDelta)(nil),             // 1: agent.TokenDelta
	(*StreamProcessResponse)(nil),  // 2: agent.StreamProcessResponse
	(*ProgressUpdate)(nil),         // 3: agent.ProgressUpdate
	(*ProcessRequestRequest)(nil),  // 4: agent.ProcessRequestRequest
	(*UpdateConfigRequest)(nil),    // 5: agent.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),   // 6: agent.UpdateConfigResponse
	(*ProcessRequestResponse)(nil), // 7: agent.ProcessRequestResponse
	(*FileChange)(nil),             // 8: agent.FileChange
	(*RoutingMetadata)(nil),        // 9: agent.RoutingMetadata
	(*ListModelsRequest)(nil),      // 10: agent.ListModelsRequest
	(*ModelInfo)(nil),              // 11: agent.ModelInfo
	(*ListModelsResponse)(nil),     // 12: agent.ListModelsResponse
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: agent.StreamProcessResponse.progress:type_name -> agent.ProgressUpdate
	7,  // 1: agent.StreamProcessResponse.final_response:type_name -> agent.ProcessRequestResponse
	1,  // 2: agent.StreamProcessResponse.token_delta:type_name -> agent.TokenDelta
	8,  // 3: agent.ProcessRequestResponse.file_changes:type_name -> agent.FileChange
	9,  // 4: agent.ProcessRequestResponse.routing_metadata:type_name -> agent.RoutingMetadata
	0,  // 5: agent.FileChange.action:type_name -> agent.FileAction
	11, // 6: agent.ListModelsResponse.models:type_name -> agent.ModelInfo
	4,  // 7: agent.Agent.ProcessRequest:input_type -> agent.ProcessRequestRequest
	4,  // 8: agent.Agent.StreamProcessRequest:input_type -> agent.ProcessRequestRequest
	5,  // 9: agent.Agent.UpdateConfig:input_type -> agent.UpdateConfigRequest
	10, // 10: agent.Agent.ListModels:input_type -> agent.ListModelsRequest
	7,  // 11: agent.Agent.ProcessRequest:output_type -> agent.ProcessRequestResponse
	2,  // 12: agent.Agent.StreamProcessRequest:output_type -> agent.StreamProcessResponse
	6,  // 13: agent.Agent.UpdateConfig:output_type -> agent.UpdateConfigResponse
	12, // 14: agent.Agent.ListModels:output_type -> agent.ListModelsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamProcessResponse_Progress)(nil),
		(*StreamProcessResponse_FinalResponse)(nil),
		(*StreamProcessResponse_TokenDelta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
