// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: source/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible actions for a FileChange.
type FileAction int32

const (
	FileAction_CREATE FileAction = 0
	FileAction_UPDATE FileAction = 1
	FileAction_DELETE FileAction = 2
)

// Enum value maps for FileAction.
var (
	FileAction_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	FileAction_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x FileAction) Enum() *FileAction {
	p := new(FileAction)
	*p = x
	return p
}

func (x FileAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileAction) Descriptor() protoreflect.EnumDescriptor {
	return file_source_proto_agent_proto_enumTypes[0].Descriptor()
}

func (FileAction) Type() protoreflect.EnumType {
	return &file_source_proto_agent_proto_enumTypes[0]
}

func (x FileAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileAction.Descriptor instead.
func (FileAction) EnumDescriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{0}
}

// Incremental token from LLM streaming.
type TokenDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDelta) Reset() {
	*x = TokenDelta{}
	mi := &file_source_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDelta) ProtoMessage() {}

func (x *TokenDelta) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDelta.ProtoReflect.Descriptor instead.
func (*TokenDelta) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TokenDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// The response message for StreamProcessRequest.
type StreamProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamProcessResponse_Progress
	//	*StreamProcessResponse_FinalResponse
	//	*StreamProcessResponse_TokenDelta
	Payload       isStreamProcessResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessResponse) Reset() {
	*x = StreamProcessResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessResponse) ProtoMessage() {}

func (x *StreamProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessResponse.ProtoReflect.Descriptor instead.
func (*StreamProcessResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StreamProcessResponse) GetPayload() isStreamProcessResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamProcessResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*StreamProcessResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *StreamProcessResponse) GetFinalResponse() *ProcessRequestResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamProcessResponse_FinalResponse); ok {
			return x.FinalResponse
		}
	}
	return nil
}

func (x *StreamProcessResponse) GetTokenDelta() *TokenDelta {
	if x != nil {
		if x, ok := x.Payload.(*StreamProcessResponse_TokenDelta); ok {
			return x.TokenDelta
		}
	}
	return nil
}

type isStreamProcessResponse_Payload interface {
	isStreamProcessResponse_Payload()
}

type StreamProcessResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type StreamProcessResponse_FinalResponse struct {
	FinalResponse *ProcessRequestResponse `protobuf:"bytes,2,opt,name=final_response,json=finalResponse,proto3,oneof"`
}

type StreamProcessResponse_TokenDelta struct {
	TokenDelta *TokenDelta `protobuf:"bytes,3,opt,name=token_delta,json=tokenDelta,proto3,oneof"`
}

func (*StreamProcessResponse_Progress) isStreamProcessResponse_Payload() {}

func (*StreamProcessResponse_FinalResponse) isStreamProcessResponse_Payload() {}

func (*StreamProcessResponse_TokenDelta) isStreamProcessResponse_Payload() {}

// Progress update during a long-running task.
type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_source_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message for ProcessRequest.
type ProcessRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Input string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // User input or query
	// Field 2 removed (was CloudProviderConfig provider_config)
	WorkDir        string `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`                      // Optional working directory for agentic tasks
	FileName       string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                   // Optional filename for agentic tasks
	ConversationId string `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Optional conversation ID for multi-turn history
	DirectLocal    bool   `protobuf:"varint,6,opt,name=direct_local,json=directLocal,proto3" json:"direct_local,omitempty"`         // Skip SmartRouter, go directly to local provider
	ModelOverride  string `protobuf:"bytes,7,opt,name=model_override,json=modelOverride,proto3" json:"model_override,omitempty"`    // Use this model instead of the configured default (temporary, per-request)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessRequestRequest) Reset() {
	*x = ProcessRequestRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestRequest) ProtoMessage() {}

func (x *ProcessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequestRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequestRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessRequestRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ProcessRequestRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ProcessRequestRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ProcessRequestRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ProcessRequestRequest) GetDirectLocal() bool {
	if x != nil {
		return x.DirectLocal
	}
	return false
}

func (x *ProcessRequestRequest) GetModelOverride() string {
	if x != nil {
		return x.ModelOverride
	}
	return ""
}

// Runtime configuration update request.
type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalModel    string                 `protobuf:"bytes,1,opt,name=local_model,json=localModel,proto3" json:"local_model,omitempty"`          // Ollama model name (e.g., "qwen3-coder", "GLM-4.7-Flash")
	CloudProvider string                 `protobuf:"bytes,2,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"` // Cloud provider name (e.g., "google", "anthropic")
	CloudModel    string                 `protobuf:"bytes,3,opt,name=cloud_model,json=cloudModel,proto3" json:"cloud_model,omitempty"`          // Cloud model name (e.g., "gemini-1.5-flash", "claude-3-opus")
	CloudApiKey   string                 `protobuf:"bytes,4,opt,name=cloud_api_key,json=cloudApiKey,proto3" json:"cloud_api_key,omitempty"`     // API key for the cloud provider
	OllamaUrl     string                 `protobuf:"bytes,5,opt,name=ollama_url,json=ollamaUrl,proto3" json:"ollama_url,omitempty"`             // Ollama endpoint URL (e.g., "http://mac-studio.local:11434")
	// Anthropic-compatible proxy URL (e.g., "http://127.0.0.1:3456" for Meridian).
	// When set, used as the baseURL for the anthropic client; api_key may be empty
	// because the proxy handles auth (Claude Max OAuth in Meridian's case).
	CloudBaseUrl  string `protobuf:"bytes,6,opt,name=cloud_base_url,json=cloudBaseUrl,proto3" json:"cloud_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConfigRequest) GetLocalModel() string {
	if x != nil {
		return x.LocalModel
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudModel() string {
	if x != nil {
		return x.CloudModel
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudApiKey() string {
	if x != nil {
		return x.CloudApiKey
	}
	return ""
}

func (x *UpdateConfigRequest) GetOllamaUrl() string {
	if x != nil {
		return x.OllamaUrl
	}
	return ""
}

func (x *UpdateConfigRequest) GetCloudBaseUrl() string {
	if x != nil {
		return x.CloudBaseUrl
	}
	return ""
}

// Runtime configuration update response.
type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message for ProcessRequest.
type ProcessRequestResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Output           string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                                             // AI generated output
	FileChanges      []*FileChange          `protobuf:"bytes,2,rep,name=file_changes,json=fileChanges,proto3" json:"file_changes,omitempty"`                // Optional structured file modifications
	RoutingMetadata  *RoutingMetadata       `protobuf:"bytes,3,opt,name=routing_metadata,json=routingMetadata,proto3" json:"routing_metadata,omitempty"`    // Optional metadata about the model/routing
	ValidationErrors string                 `protobuf:"bytes,4,opt,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"` // Optional captured validation errors (e.g. test failures)
	InputTokens      int32                  `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`               // Prompt tokens consumed
	OutputTokens     int32                  `protobuf:"varint,6,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`            // Completion tokens generated
	// Non-fatal informational message from the agent (e.g. "cloud was unavailable —
	// answered locally"). Clients render this as a system entry so the user always
	// knows when routing did something different than the SmartRouter requested.
	Notice        string `protobuf:"bytes,7,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequestResponse) Reset() {
	*x = ProcessRequestResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestResponse) ProtoMessage() {}

func (x *ProcessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequestResponse.ProtoReflect.Descriptor instead.
func (*ProcessRequestResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessRequestResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ProcessRequestResponse) GetFileChanges() []*FileChange {
	if x != nil {
		return x.FileChanges
	}
	return nil
}

func (x *ProcessRequestResponse) GetRoutingMetadata() *RoutingMetadata {
	if x != nil {
		return x.RoutingMetadata
	}
	return nil
}

func (x *ProcessRequestResponse) GetValidationErrors() string {
	if x != nil {
		return x.ValidationErrors
	}
	return ""
}

func (x *ProcessRequestResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *ProcessRequestResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *ProcessRequestResponse) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

// Represents a change to a specific file.
type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                            // File path (relative to work_dir)
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // New file content
	Action        FileAction             `protobuf:"varint,3,opt,name=action,proto3,enum=agent.FileAction" json:"action,omitempty"` // Type of action to perform
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_source_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FileChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChange) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileChange) GetAction() FileAction {
	if x != nil {
		return x.Action
	}
	return FileAction_CREATE
}

// Metadata about the routing and model execution.
type RoutingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`     // Name of the model that processed the request
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                  // Confidence score for the routing decision
	Escalated     bool                   `protobuf:"varint,3,opt,name=escalated,proto3" json:"escalated,omitempty"`                     // Whether the request was escalated to cloud
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                        // Active Ollama endpoint URL that served the request
	IsFallback    bool                   `protobuf:"varint,5,opt,name=is_fallback,json=isFallback,proto3" json:"is_fallback,omitempty"` // Whether the fallback (local) endpoint was used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingMetadata) Reset() {
	*x = RoutingMetadata{}
	mi := &file_source_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingMetadata) ProtoMessage() {}

func (x *RoutingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingMetadata.ProtoReflect.Descriptor instead.
func (*RoutingMetadata) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RoutingMetadata) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RoutingMetadata) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RoutingMetadata) GetEscalated() bool {
	if x != nil {
		return x.Escalated
	}
	return false
}

func (x *RoutingMetadata) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RoutingMetadata) GetIsFallback() bool {
	if x != nil {
		return x.IsFallback
	}
	return false
}

// Request to list available models on the active Ollama instance.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{9}
}

// A single model available on an Ollama instance.
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Model name (e.g., "qwen3-coder:latest")
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                              // Model size in bytes
	ModifiedAt    string                 `protobuf:"bytes,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"` // Last modified timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_source_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ModelInfo) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

// Response containing available models.
type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// Request to list available Agent Skills.
// GetConfig returns the current runtime config to the caller. The API key
// is reported as a presence bool only — the literal value never leaves the
// agent so a curious client can't dump someone else's secrets.
// Conversation is the persisted summary returned by ListConversations.
type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,3,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // unix seconds
	LastTurnAt    int64                  `protobuf:"varint,6,opt,name=last_turn_at,json=lastTurnAt,proto3" json:"last_turn_at,omitempty"`
	TurnCount     int32                  `protobuf:"varint,7,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_source_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *Conversation) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Conversation) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Conversation) GetLastTurnAt() int64 {
	if x != nil {
		return x.LastTurnAt
	}
	return 0
}

func (x *Conversation) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

// PersistedTurn is one stored role-emission returned by Resume.
type PersistedTurn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant" | "system"
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TokensIn       int32                  `protobuf:"varint,5,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut      int32                  `protobuf:"varint,6,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	LatencyMs      int32                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersistedTurn) Reset() {
	*x = PersistedTurn{}
	mi := &file_source_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedTurn) ProtoMessage() {}

func (x *PersistedTurn) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedTurn.ProtoReflect.Descriptor instead.
func (*PersistedTurn) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PersistedTurn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersistedTurn) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PersistedTurn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PersistedTurn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PersistedTurn) GetTokensIn() int32 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *PersistedTurn) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

func (x *PersistedTurn) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PersistedTurn) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"` // empty matches all
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // 0 = no cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ListConversationsRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type ResumeConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeConversationRequest) Reset() {
	*x = ResumeConversationRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeConversationRequest) ProtoMessage() {}

func (x *ResumeConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeConversationRequest.ProtoReflect.Descriptor instead.
func (*ResumeConversationRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ResumeConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turns         []*PersistedTurn       `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeConversationResponse) Reset() {
	*x = ResumeConversationResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeConversationResponse) ProtoMessage() {}

func (x *ResumeConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeConversationResponse.ProtoReflect.Descriptor instead.
func (*ResumeConversationResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ResumeConversationResponse) GetTurns() []*PersistedTurn {
	if x != nil {
		return x.Turns
	}
	return nil
}

type DeleteConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResponse) Reset() {
	*x = DeleteConversationResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResponse) ProtoMessage() {}

func (x *DeleteConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteConversationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RenameConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenameConversationRequest) Reset() {
	*x = RenameConversationRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameConversationRequest) ProtoMessage() {}

func (x *RenameConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameConversationRequest.ProtoReflect.Descriptor instead.
func (*RenameConversationRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RenameConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RenameConversationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RenameConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameConversationResponse) Reset() {
	*x = RenameConversationResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameConversationResponse) ProtoMessage() {}

func (x *RenameConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameConversationResponse.ProtoReflect.Descriptor instead.
func (*RenameConversationResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *RenameConversationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{22}
}

type GetConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OllamaUrl      string                 `protobuf:"bytes,1,opt,name=ollama_url,json=ollamaUrl,proto3" json:"ollama_url,omitempty"`
	LocalModel     string                 `protobuf:"bytes,2,opt,name=local_model,json=localModel,proto3" json:"local_model,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	CloudProvider  string                 `protobuf:"bytes,4,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	CloudModel     string                 `protobuf:"bytes,5,opt,name=cloud_model,json=cloudModel,proto3" json:"cloud_model,omitempty"`
	CloudBaseUrl   string                 `protobuf:"bytes,6,opt,name=cloud_base_url,json=cloudBaseUrl,proto3" json:"cloud_base_url,omitempty"`
	CloudApiKeySet bool                   `protobuf:"varint,7,opt,name=cloud_api_key_set,json=cloudApiKeySet,proto3" json:"cloud_api_key_set,omitempty"`
	// Last observed cloud state: "ok", "absent", "error". Reflects whether the
	// most recent turn succeeded; useful for surfacing in the CLI status bar.
	CloudState    string `protobuf:"bytes,8,opt,name=cloud_state,json=cloudState,proto3" json:"cloud_state,omitempty"`
	Port          string `protobuf:"bytes,9,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *GetConfigResponse) GetOllamaUrl() string {
	if x != nil {
		return x.OllamaUrl
	}
	return ""
}

func (x *GetConfigResponse) GetLocalModel() string {
	if x != nil {
		return x.LocalModel
	}
	return ""
}

func (x *GetConfigResponse) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *GetConfigResponse) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *GetConfigResponse) GetCloudModel() string {
	if x != nil {
		return x.CloudModel
	}
	return ""
}

func (x *GetConfigResponse) GetCloudBaseUrl() string {
	if x != nil {
		return x.CloudBaseUrl
	}
	return ""
}

func (x *GetConfigResponse) GetCloudApiKeySet() bool {
	if x != nil {
		return x.CloudApiKeySet
	}
	return false
}

func (x *GetConfigResponse) GetCloudState() string {
	if x != nil {
		return x.CloudState
	}
	return ""
}

func (x *GetConfigResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{24}
}

// A single skill in the catalog.
type SkillInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Skill name (matches directory name)
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // What the skill does and when to use it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInfo) Reset() {
	*x = SkillInfo{}
	mi := &file_source_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInfo) ProtoMessage() {}

func (x *SkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInfo.ProtoReflect.Descriptor instead.
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *SkillInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response containing available skills.
type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*SkillInfo           `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *ListSkillsResponse) GetSkills() []*SkillInfo {
	if x != nil {
		return x.Skills
	}
	return nil
}

// Request to get a specific skill's full definition.
type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Skill name to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_source_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *GetSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response containing the full skill definition.
type GetSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // Skill name
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Full SKILL.md file content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_source_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_source_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *GetSkillResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSkillResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_source_proto_agent_proto protoreflect.FileDescriptor

const file_source_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x18source/proto/agent.proto\x12\x05agent\"&\n" +
	"\n" +
	"TokenDelta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xd5\x01\n" +
	"\x15StreamProcessResponse\x123\n" +
	"\bprogress\x18\x01 \x01(\v2\x15.agent.ProgressUpdateH\x00R\bprogress\x12F\n" +
	"\x0efinal_response\x18\x02 \x01(\v2\x1d.agent.ProcessRequestResponseH\x00R\rfinalResponse\x124\n" +
	"\vtoken_delta\x18\x03 \x01(\v2\x11.agent.TokenDeltaH\x00R\n" +
	"tokenDeltaB\t\n" +
	"\apayload\"*\n" +
	"\x0eProgressUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd8\x01\n" +
	"\x15ProcessRequestRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12!\n" +
	"\fdirect_local\x18\x06 \x01(\bR\vdirectLocal\x12%\n" +
	"\x0emodel_override\x18\a \x01(\tR\rmodelOverride\"\xe7\x01\n" +
	"\x13UpdateConfigRequest\x12\x1f\n" +
	"\vlocal_model\x18\x01 \x01(\tR\n" +
	"localModel\x12%\n" +
	"\x0ecloud_provider\x18\x02 \x01(\tR\rcloudProvider\x12\x1f\n" +
	"\vcloud_model\x18\x03 \x01(\tR\n" +
	"cloudModel\x12\"\n" +
	"\rcloud_api_key\x18\x04 \x01(\tR\vcloudApiKey\x12\x1d\n" +
	"\n" +
	"ollama_url\x18\x05 \x01(\tR\tollamaUrl\x12$\n" +
	"\x0ecloud_base_url\x18\x06 \x01(\tR\fcloudBaseUrl\"J\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb6\x02\n" +
	"\x16ProcessRequestResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x124\n" +
	"\ffile_changes\x18\x02 \x03(\v2\x11.agent.FileChangeR\vfileChanges\x12A\n" +
	"\x10routing_metadata\x18\x03 \x01(\v2\x16.agent.RoutingMetadataR\x0froutingMetadata\x12+\n" +
	"\x11validation_errors\x18\x04 \x01(\tR\x10validationErrors\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x01(\x05R\foutputTokens\x12\x16\n" +
	"\x06notice\x18\a \x01(\tR\x06notice\"e\n" +
	"\n" +
	"FileChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12)\n" +
	"\x06action\x18\x03 \x01(\x0e2\x11.agent.FileActionR\x06action\"\xab\x01\n" +
	"\x0fRoutingMetadata\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\tescalated\x18\x03 \x01(\bR\tescalated\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vis_fallback\x18\x05 \x01(\bR\n" +
	"isFallback\"\x13\n" +
	"\x11ListModelsRequest\"T\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x03 \x01(\tR\n" +
	"modifiedAt\">\n" +
	"\x12ListModelsResponse\x12(\n" +
	"\x06models\x18\x01 \x03(\v2\x10.agent.ModelInfoR\x06models\"\xcb\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vproject_dir\x18\x03 \x01(\tR\n" +
	"projectDir\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12 \n" +
	"\flast_turn_at\x18\x06 \x01(\x03R\n" +
	"lastTurnAt\x12\x1d\n" +
	"\n" +
	"turn_count\x18\a \x01(\x05R\tturnCount\"\xf0\x01\n" +
	"\rPersistedTurn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\ttokens_in\x18\x05 \x01(\x05R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\x06 \x01(\x05R\ttokensOut\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"Q\n" +
	"\x18ListConversationsRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"V\n" +
	"\x19ListConversationsResponse\x129\n" +
	"\rconversations\x18\x01 \x03(\v2\x13.agent.ConversationR\rconversations\"D\n" +
	"\x19ResumeConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"H\n" +
	"\x1aResumeConversationResponse\x12*\n" +
	"\x05turns\x18\x01 \x03(\v2\x14.agent.PersistedTurnR\x05turns\"D\n" +
	"\x19DeleteConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\",\n" +
	"\x1aDeleteConversationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Z\n" +
	"\x19RenameConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\",\n" +
	"\x1aRenameConversationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x12\n" +
	"\x10GetConfigRequest\"\xca\x02\n" +
	"\x11GetConfigResponse\x12\x1d\n" +
	"\n" +
	"ollama_url\x18\x01 \x01(\tR\tollamaUrl\x12\x1f\n" +
	"\vlocal_model\x18\x02 \x01(\tR\n" +
	"localModel\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel\x12%\n" +
	"\x0ecloud_provider\x18\x04 \x01(\tR\rcloudProvider\x12\x1f\n" +
	"\vcloud_model\x18\x05 \x01(\tR\n" +
	"cloudModel\x12$\n" +
	"\x0ecloud_base_url\x18\x06 \x01(\tR\fcloudBaseUrl\x12)\n" +
	"\x11cloud_api_key_set\x18\a \x01(\bR\x0ecloudApiKeySet\x12\x1f\n" +
	"\vcloud_state\x18\b \x01(\tR\n" +
	"cloudState\x12\x12\n" +
	"\x04port\x18\t \x01(\tR\x04port\"\x13\n" +
	"\x11ListSkillsRequest\"A\n" +
	"\tSkillInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\">\n" +
	"\x12ListSkillsResponse\x12(\n" +
	"\x06skills\x18\x01 \x03(\v2\x10.agent.SkillInfoR\x06skills\"%\n" +
	"\x0fGetSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x10GetSkillResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent*0\n" +
	"\n" +
	"FileAction\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\xf7\x06\n" +
	"\x05Agent\x12O\n" +
	"\x0eProcessRequest\x12\x1c.agent.ProcessRequestRequest\x1a\x1d.agent.ProcessRequestResponse\"\x00\x12V\n" +
	"\x14StreamProcessRequest\x12\x1c.agent.ProcessRequestRequest\x1a\x1c.agent.StreamProcessResponse\"\x000\x01\x12I\n" +
	"\fUpdateConfig\x12\x1a.agent.UpdateConfigRequest\x1a\x1b.agent.UpdateConfigResponse\"\x00\x12@\n" +
	"\tGetConfig\x12\x17.agent.GetConfigRequest\x1a\x18.agent.GetConfigResponse\"\x00\x12X\n" +
	"\x11ListConversations\x12\x1f.agent.ListConversationsRequest\x1a .agent.ListConversationsResponse\"\x00\x12[\n" +
	"\x12ResumeConversation\x12 .agent.ResumeConversationRequest\x1a!.agent.ResumeConversationResponse\"\x00\x12[\n" +
	"\x12DeleteConversation\x12 .agent.DeleteConversationRequest\x1a!.agent.DeleteConversationResponse\"\x00\x12[\n" +
	"\x12RenameConversation\x12 .agent.RenameConversationRequest\x1a!.agent.RenameConversationResponse\"\x00\x12C\n" +
	"\n" +
	"ListModels\x12\x18.agent.ListModelsRequest\x1a\x19.agent.ListModelsResponse\"\x00\x12C\n" +
	"\n" +
	"ListSkills\x12\x18.agent.ListSkillsRequest\x1a\x19.agent.ListSkillsResponse\"\x00\x12=\n" +
	"\bGetSkill\x12\x16.agent.GetSkillRequest\x1a\x17.agent.GetSkillResponse\"\x00B!Z\x1fcercano/source/server/pkg/protob\x06proto3"

var (
	file_source_proto_agent_proto_rawDescOnce sync.Once
	file_source_proto_agent_proto_rawDescData []byte
)

func file_source_proto_agent_proto_rawDescGZIP() []byte {
	file_source_proto_agent_proto_rawDescOnce.Do(func() {
		file_source_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_source_proto_agent_proto_rawDesc), len(file_source_proto_agent_proto_rawDesc)))
	})
	return file_source_proto_agent_proto_rawDescData
}

var file_source_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_source_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_source_proto_agent_proto_goTypes = []any{
	(FileAction)(0),                    // 0: agent.FileAction
	(*TokenDelta)(nil),                 // 1: agent.TokenDelta
	(*StreamProcessResponse)(nil),      // 2: agent.StreamProcessResponse
	(*ProgressUpdate)(nil),             // 3: agent.ProgressUpdate
	(*ProcessRequestRequest)(nil),      // 4: agent.ProcessRequestRequest
	(*UpdateConfigRequest)(nil),        // 5: agent.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),       // 6: agent.UpdateConfigResponse
	(*ProcessRequestResponse)(nil),     // 7: agent.ProcessRequestResponse
	(*FileChange)(nil),                 // 8: agent.FileChange
	(*RoutingMetadata)(nil),            // 9: agent.RoutingMetadata
	(*ListModelsRequest)(nil),          // 10: agent.ListModelsRequest
	(*ModelInfo)(nil),                  // 11: agent.ModelInfo
	(*ListModelsResponse)(nil),         // 12: agent.ListModelsResponse
	(*Conversation)(nil),               // 13: agent.Conversation
	(*PersistedTurn)(nil),              // 14: agent.PersistedTurn
	(*ListConversationsRequest)(nil),   // 15: agent.ListConversationsRequest
	(*ListConversationsResponse)(nil),  // 16: agent.ListConversationsResponse
	(*ResumeConversationRequest)(nil),  // 17: agent.ResumeConversationRequest
	(*ResumeConversationResponse)(nil), // 18: agent.ResumeConversationResponse
	(*DeleteConversationRequest)(nil),  // 19: agent.DeleteConversationRequest
	(*DeleteConversationResponse)(nil), // 20: agent.DeleteConversationResponse
	(*RenameConversationRequest)(nil),  // 21: agent.RenameConversationRequest
	(*RenameConversationResponse)(nil), // 22: agent.RenameConversationResponse
	(*GetConfigRequest)(nil),           // 23: agent.GetConfigRequest
	(*GetConfigResponse)(nil),          // 24: agent.GetConfigResponse
	(*ListSkillsRequest)(nil),          // 25: agent.ListSkillsRequest
	(*SkillInfo)(nil),                  // 26: agent.SkillInfo
	(*ListSkillsResponse)(nil),         // 27: agent.ListSkillsResponse
	(*GetSkillRequest)(nil),            // 28: agent.GetSkillRequest
	(*GetSkillResponse)(nil),           // 29: agent.GetSkillResponse
}
var file_source_proto_agent_proto_depIdxs = []int32{
	3,  // 0: agent.StreamProcessResponse.progress:type_name -> agent.ProgressUpdate
	7,  // 1: agent.StreamProcessResponse.final_response:type_name -> agent.ProcessRequestResponse
	1,  // 2: agent.StreamProcessResponse.token_delta:type_name -> agent.TokenDelta
	8,  // 3: agent.ProcessRequestResponse.file_changes:type_name -> agent.FileChange
	9,  // 4: agent.ProcessRequestResponse.routing_metadata:type_name -> agent.RoutingMetadata
	0,  // 5: agent.FileChange.action:type_name -> agent.FileAction
	11, // 6: agent.ListModelsResponse.models:type_name -> agent.ModelInfo
	13, // 7: agent.ListConversationsResponse.conversations:type_name -> agent.Conversation
	14, // 8: agent.ResumeConversationResponse.turns:type_name -> agent.PersistedTurn
	26, // 9: agent.ListSkillsResponse.skills:type_name -> agent.SkillInfo
	4,  // 10: agent.Agent.ProcessRequest:input_type -> agent.ProcessRequestRequest
	4,  // 11: agent.Agent.StreamProcessRequest:input_type -> agent.ProcessRequestRequest
	5,  // 12: agent.Agent.UpdateConfig:input_type -> agent.UpdateConfigRequest
	23, // 13: agent.Agent.GetConfig:input_type -> agent.GetConfigRequest
	15, // 14: agent.Agent.ListConversations:input_type -> agent.ListConversationsRequest
	17, // 15: agent.Agent.ResumeConversation:input_type -> agent.ResumeConversationRequest
	19, // 16: agent.Agent.DeleteConversation:input_type -> agent.DeleteConversationRequest
	21, // 17: agent.Agent.RenameConversation:input_type -> agent.RenameConversationRequest
	10, // 18: agent.Agent.ListModels:input_type -> agent.ListModelsRequest
	25, // 19: agent.Agent.ListSkills:input_type -> agent.ListSkillsRequest
	28, // 20: agent.Agent.GetSkill:input_type -> agent.GetSkillRequest
	7,  // 21: agent.Agent.ProcessRequest:output_type -> agent.ProcessRequestResponse
	2,  // 22: agent.Agent.StreamProcessRequest:output_type -> agent.StreamProcessResponse
	6,  // 23: agent.Agent.UpdateConfig:output_type -> agent.UpdateConfigResponse
	24, // 24: agent.Agent.GetConfig:output_type -> agent.GetConfigResponse
	16, // 25: agent.Agent.ListConversations:output_type -> agent.ListConversationsResponse
	18, // 26: agent.Agent.ResumeConversation:output_type -> agent.ResumeConversationResponse
	20, // 27: agent.Agent.DeleteConversation:output_type -> agent.DeleteConversationResponse
	22, // 28: agent.Agent.RenameConversation:output_type -> agent.RenameConversationResponse
	12, // 29: agent.Agent.ListModels:output_type -> agent.ListModelsResponse
	27, // 30: agent.Agent.ListSkills:output_type -> agent.ListSkillsResponse
	29, // 31: agent.Agent.GetSkill:output_type -> agent.GetSkillResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_source_proto_agent_proto_init() }
func file_source_proto_agent_proto_init() {
	if File_source_proto_agent_proto != nil {
		return
	}
	file_source_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamProcessResponse_Progress)(nil),
		(*StreamProcessResponse_FinalResponse)(nil),
		(*StreamProcessResponse_TokenDelta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_source_proto_agent_proto_rawDesc), len(file_source_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_source_proto_agent_proto_goTypes,
		DependencyIndexes: file_source_proto_agent_proto_depIdxs,
		EnumInfos:         file_source_proto_agent_proto_enumTypes,
		MessageInfos:      file_source_proto_agent_proto_msgTypes,
	}.Build()
	File_source_proto_agent_proto = out.File
	file_source_proto_agent_proto_goTypes = nil
	file_source_proto_agent_proto_depIdxs = nil
}
