// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: source/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_ProcessRequest_FullMethodName             = "/agent.Agent/ProcessRequest"
	Agent_StreamProcessRequest_FullMethodName       = "/agent.Agent/StreamProcessRequest"
	Agent_UpdateConfig_FullMethodName               = "/agent.Agent/UpdateConfig"
	Agent_GetConfig_FullMethodName                  = "/agent.Agent/GetConfig"
	Agent_ListConversations_FullMethodName          = "/agent.Agent/ListConversations"
	Agent_ResumeConversation_FullMethodName         = "/agent.Agent/ResumeConversation"
	Agent_DeleteConversation_FullMethodName         = "/agent.Agent/DeleteConversation"
	Agent_RenameConversation_FullMethodName         = "/agent.Agent/RenameConversation"
	Agent_GetConversation_FullMethodName            = "/agent.Agent/GetConversation"
	Agent_GetContextUsage_FullMethodName            = "/agent.Agent/GetContextUsage"
	Agent_GetCompactionState_FullMethodName         = "/agent.Agent/GetCompactionState"
	Agent_ExportContext_FullMethodName              = "/agent.Agent/ExportContext"
	Agent_GetConversationTurns_FullMethodName       = "/agent.Agent/GetConversationTurns"
	Agent_ListTools_FullMethodName                  = "/agent.Agent/ListTools"
	Agent_InvokeTool_FullMethodName                 = "/agent.Agent/InvokeTool"
	Agent_ListModels_FullMethodName                 = "/agent.Agent/ListModels"
	Agent_GetRuntimeStatus_FullMethodName           = "/agent.Agent/GetRuntimeStatus"
	Agent_ListRuntimeModels_FullMethodName          = "/agent.Agent/ListRuntimeModels"
	Agent_ListRuntimeEndpoints_FullMethodName       = "/agent.Agent/ListRuntimeEndpoints"
	Agent_StartRuntimeModel_FullMethodName          = "/agent.Agent/StartRuntimeModel"
	Agent_StopRuntimeModel_FullMethodName           = "/agent.Agent/StopRuntimeModel"
	Agent_RestartRuntime_FullMethodName             = "/agent.Agent/RestartRuntime"
	Agent_DownloadRuntimeModel_FullMethodName       = "/agent.Agent/DownloadRuntimeModel"
	Agent_CancelRuntimeModelDownload_FullMethodName = "/agent.Agent/CancelRuntimeModelDownload"
	Agent_DeleteRuntimeModel_FullMethodName         = "/agent.Agent/DeleteRuntimeModel"
	Agent_StreamRuntimeLogs_FullMethodName          = "/agent.Agent/StreamRuntimeLogs"
	Agent_ListSkills_FullMethodName                 = "/agent.Agent/ListSkills"
	Agent_GetSkill_FullMethodName                   = "/agent.Agent/GetSkill"
	Agent_SetPermissionMode_FullMethodName          = "/agent.Agent/SetPermissionMode"
	Agent_GetPermissionMode_FullMethodName          = "/agent.Agent/GetPermissionMode"
	Agent_SubscribeEvents_FullMethodName            = "/agent.Agent/SubscribeEvents"
	Agent_AllowToolCall_FullMethodName              = "/agent.Agent/AllowToolCall"
	Agent_DenyToolCall_FullMethodName               = "/agent.Agent/DenyToolCall"
	Agent_GetProviderCapabilities_FullMethodName    = "/agent.Agent/GetProviderCapabilities"
	Agent_ProposeContextEdit_FullMethodName         = "/agent.Agent/ProposeContextEdit"
	Agent_DeleteConversationTurns_FullMethodName    = "/agent.Agent/DeleteConversationTurns"
	Agent_ListMcpServers_FullMethodName             = "/agent.Agent/ListMcpServers"
	Agent_AddMcpServer_FullMethodName               = "/agent.Agent/AddMcpServer"
	Agent_RemoveMcpServer_FullMethodName            = "/agent.Agent/RemoveMcpServer"
	Agent_RestartMcpServer_FullMethodName           = "/agent.Agent/RestartMcpServer"
	Agent_GetCloudProfiles_FullMethodName           = "/agent.Agent/GetCloudProfiles"
	Agent_SetActiveCloudProfile_FullMethodName      = "/agent.Agent/SetActiveCloudProfile"
	Agent_SetCloudProfileKey_FullMethodName         = "/agent.Agent/SetCloudProfileKey"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Agent service definition.
type AgentClient interface {
	// ProcessRequest handles AI requests (Unary).
	ProcessRequest(ctx context.Context, in *ProcessRequestRequest, opts ...grpc.CallOption) (*ProcessRequestResponse, error)
	// StreamProcessRequest handles AI requests with progress updates (Streaming).
	StreamProcessRequest(ctx context.Context, in *ProcessRequestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamProcessResponse], error)
	// UpdateConfig updates runtime configuration (model, provider) without server restart.
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	// GetConfig returns the current runtime config. API key is reported as a
	// presence bool only — the literal value never leaves the agent.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// Persisted-conversation surface: /history picker calls ListConversations;
	// selecting a row calls ResumeConversation; deleting a row (future) calls
	// DeleteConversation. Resume rehydrates the in-memory session store on the
	// agent so the next chat turn sees full prior context.
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	ResumeConversation(ctx context.Context, in *ResumeConversationRequest, opts ...grpc.CallOption) (*ResumeConversationResponse, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
	RenameConversation(ctx context.Context, in *RenameConversationRequest, opts ...grpc.CallOption) (*RenameConversationResponse, error)
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
	// GetContextUsage reports cumulative token usage vs. the active model's
	// context window for a conversation. The CLI status bar polls this after
	// each streamed turn.
	GetContextUsage(ctx context.Context, in *GetContextUsageRequest, opts ...grpc.CallOption) (*GetContextUsageResponse, error)
	// GetCompactionState returns the compaction summary + frozen/live split for
	// the /c context viewer.
	GetCompactionState(ctx context.Context, in *GetCompactionStateRequest, opts ...grpc.CallOption) (*GetCompactionStateResponse, error)
	// ExportContext returns the full uncapped raw history as a JSON []llm.Message.
	ExportContext(ctx context.Context, in *ExportContextRequest, opts ...grpc.CallOption) (*ExportContextResponse, error)
	// GetConversationTurns returns display-ready, side-effect-free summaries of a
	// conversation's turns for the /c context viewer. Unlike ResumeConversation
	// it does NOT re-hydrate server session state.
	GetConversationTurns(ctx context.Context, in *GetConversationTurnsRequest, opts ...grpc.CallOption) (*GetConversationTurnsResponse, error)
	// ListTools enumerates the agent's registered tools (name, description,
	// permission tier). /tools in the CLI renders this through the Table
	// primitive.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// InvokeTool executes a registered tool with JSON args and returns its
	// Result. Used by /tool <name> {...args} for direct invocation; the
	// agent's chat path will dispatch tools via this same RPC once the
	// algorithmic-dispatcher lands.
	InvokeTool(ctx context.Context, in *InvokeToolRequest, opts ...grpc.CallOption) (*InvokeToolResponse, error)
	// ListModels returns the models available on the active Ollama instance.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Runtime dashboard APIs expose managed runtimes, external endpoints, and
	// logs through Cercano rather than having the CLI call providers directly.
	GetRuntimeStatus(ctx context.Context, in *GetRuntimeStatusRequest, opts ...grpc.CallOption) (*GetRuntimeStatusResponse, error)
	ListRuntimeModels(ctx context.Context, in *ListRuntimeModelsRequest, opts ...grpc.CallOption) (*ListRuntimeModelsResponse, error)
	ListRuntimeEndpoints(ctx context.Context, in *ListRuntimeEndpointsRequest, opts ...grpc.CallOption) (*ListRuntimeEndpointsResponse, error)
	StartRuntimeModel(ctx context.Context, in *StartRuntimeModelRequest, opts ...grpc.CallOption) (*StartRuntimeModelResponse, error)
	StopRuntimeModel(ctx context.Context, in *StopRuntimeModelRequest, opts ...grpc.CallOption) (*StopRuntimeModelResponse, error)
	RestartRuntime(ctx context.Context, in *RestartRuntimeRequest, opts ...grpc.CallOption) (*RestartRuntimeResponse, error)
	DownloadRuntimeModel(ctx context.Context, in *DownloadRuntimeModelRequest, opts ...grpc.CallOption) (*DownloadRuntimeModelResponse, error)
	CancelRuntimeModelDownload(ctx context.Context, in *CancelRuntimeModelDownloadRequest, opts ...grpc.CallOption) (*CancelRuntimeModelDownloadResponse, error)
	DeleteRuntimeModel(ctx context.Context, in *DeleteRuntimeModelRequest, opts ...grpc.CallOption) (*DeleteRuntimeModelResponse, error)
	StreamRuntimeLogs(ctx context.Context, in *StreamRuntimeLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeLogEntry], error)
	// ListSkills returns the catalog of available Agent Skills (name + description).
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	// GetSkill returns the full SKILL.md content for a specific skill by name.
	GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error)
	// SetPermissionMode changes the agent's session permission mode.
	SetPermissionMode(ctx context.Context, in *SetPermissionModeRequest, opts ...grpc.CallOption) (*SetPermissionModeResponse, error)
	// GetPermissionMode reads the current mode.
	GetPermissionMode(ctx context.Context, in *GetPermissionModeRequest, opts ...grpc.CallOption) (*GetPermissionModeResponse, error)
	// SubscribeEvents is a standing server->client stream the client holds open
	// for its whole session. The agent pushes unsolicited state changes here so
	// clients never poll. First event type is PermissionModeChanged (fired when
	// the mode is changed via SetPermissionMode by any client, or when the
	// permissions file is edited out-of-band by a human or a tool).
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientEvent], error)
	// AllowToolCall + DenyToolCall are how a client replies to a
	// PermissionRequired stream event.
	AllowToolCall(ctx context.Context, in *AllowToolCallRequest, opts ...grpc.CallOption) (*AllowToolCallResponse, error)
	DenyToolCall(ctx context.Context, in *DenyToolCallRequest, opts ...grpc.CallOption) (*DenyToolCallResponse, error)
	// GetProviderCapabilities reports what the active provider supports.
	GetProviderCapabilities(ctx context.Context, in *GetProviderCapabilitiesRequest, opts ...grpc.CallOption) (*GetProviderCapabilitiesResponse, error)
	// ProposeContextEdit runs the picker model over a conversation's turn summaries
	// and returns a validated deletion proposal. Read-only — no turns are deleted.
	ProposeContextEdit(ctx context.Context, in *ProposeContextEditRequest, opts ...grpc.CallOption) (*ProposeContextEditResponse, error)
	// DeleteConversationTurns hard-deletes the named turns from a conversation.
	DeleteConversationTurns(ctx context.Context, in *DeleteConversationTurnsRequest, opts ...grpc.CallOption) (*DeleteConversationTurnsResponse, error)
	// ---- MCP host ----
	ListMcpServers(ctx context.Context, in *ListMcpServersRequest, opts ...grpc.CallOption) (*ListMcpServersResponse, error)
	AddMcpServer(ctx context.Context, in *AddMcpServerRequest, opts ...grpc.CallOption) (*AddMcpServerResponse, error)
	RemoveMcpServer(ctx context.Context, in *RemoveMcpServerRequest, opts ...grpc.CallOption) (*RemoveMcpServerResponse, error)
	RestartMcpServer(ctx context.Context, in *RestartMcpServerRequest, opts ...grpc.CallOption) (*RestartMcpServerResponse, error)
	// ---- Cloud profile management ----
	GetCloudProfiles(ctx context.Context, in *GetCloudProfilesRequest, opts ...grpc.CallOption) (*GetCloudProfilesResponse, error)
	SetActiveCloudProfile(ctx context.Context, in *SetActiveCloudProfileRequest, opts ...grpc.CallOption) (*SetActiveCloudProfileResponse, error)
	SetCloudProfileKey(ctx context.Context, in *SetCloudProfileKeyRequest, opts ...grpc.CallOption) (*SetCloudProfileKeyResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) ProcessRequest(ctx context.Context, in *ProcessRequestRequest, opts ...grpc.CallOption) (*ProcessRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessRequestResponse)
	err := c.cc.Invoke(ctx, Agent_ProcessRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StreamProcessRequest(ctx context.Context, in *ProcessRequestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamProcessResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_StreamProcessRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessRequestRequest, StreamProcessResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_StreamProcessRequestClient = grpc.ServerStreamingClient[StreamProcessResponse]

func (c *agentClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, Agent_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, Agent_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, Agent_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ResumeConversation(ctx context.Context, in *ResumeConversationRequest, opts ...grpc.CallOption) (*ResumeConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeConversationResponse)
	err := c.cc.Invoke(ctx, Agent_ResumeConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResponse)
	err := c.cc.Invoke(ctx, Agent_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RenameConversation(ctx context.Context, in *RenameConversationRequest, opts ...grpc.CallOption) (*RenameConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameConversationResponse)
	err := c.cc.Invoke(ctx, Agent_RenameConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conversation)
	err := c.cc.Invoke(ctx, Agent_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetContextUsage(ctx context.Context, in *GetContextUsageRequest, opts ...grpc.CallOption) (*GetContextUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextUsageResponse)
	err := c.cc.Invoke(ctx, Agent_GetContextUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetCompactionState(ctx context.Context, in *GetCompactionStateRequest, opts ...grpc.CallOption) (*GetCompactionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompactionStateResponse)
	err := c.cc.Invoke(ctx, Agent_GetCompactionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ExportContext(ctx context.Context, in *ExportContextRequest, opts ...grpc.CallOption) (*ExportContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportContextResponse)
	err := c.cc.Invoke(ctx, Agent_ExportContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetConversationTurns(ctx context.Context, in *GetConversationTurnsRequest, opts ...grpc.CallOption) (*GetConversationTurnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationTurnsResponse)
	err := c.cc.Invoke(ctx, Agent_GetConversationTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, Agent_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) InvokeTool(ctx context.Context, in *InvokeToolRequest, opts ...grpc.CallOption) (*InvokeToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeToolResponse)
	err := c.cc.Invoke(ctx, Agent_InvokeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Agent_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetRuntimeStatus(ctx context.Context, in *GetRuntimeStatusRequest, opts ...grpc.CallOption) (*GetRuntimeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeStatusResponse)
	err := c.cc.Invoke(ctx, Agent_GetRuntimeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListRuntimeModels(ctx context.Context, in *ListRuntimeModelsRequest, opts ...grpc.CallOption) (*ListRuntimeModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimeModelsResponse)
	err := c.cc.Invoke(ctx, Agent_ListRuntimeModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListRuntimeEndpoints(ctx context.Context, in *ListRuntimeEndpointsRequest, opts ...grpc.CallOption) (*ListRuntimeEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimeEndpointsResponse)
	err := c.cc.Invoke(ctx, Agent_ListRuntimeEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StartRuntimeModel(ctx context.Context, in *StartRuntimeModelRequest, opts ...grpc.CallOption) (*StartRuntimeModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRuntimeModelResponse)
	err := c.cc.Invoke(ctx, Agent_StartRuntimeModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopRuntimeModel(ctx context.Context, in *StopRuntimeModelRequest, opts ...grpc.CallOption) (*StopRuntimeModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRuntimeModelResponse)
	err := c.cc.Invoke(ctx, Agent_StopRuntimeModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RestartRuntime(ctx context.Context, in *RestartRuntimeRequest, opts ...grpc.CallOption) (*RestartRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartRuntimeResponse)
	err := c.cc.Invoke(ctx, Agent_RestartRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DownloadRuntimeModel(ctx context.Context, in *DownloadRuntimeModelRequest, opts ...grpc.CallOption) (*DownloadRuntimeModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadRuntimeModelResponse)
	err := c.cc.Invoke(ctx, Agent_DownloadRuntimeModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CancelRuntimeModelDownload(ctx context.Context, in *CancelRuntimeModelDownloadRequest, opts ...grpc.CallOption) (*CancelRuntimeModelDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRuntimeModelDownloadResponse)
	err := c.cc.Invoke(ctx, Agent_CancelRuntimeModelDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteRuntimeModel(ctx context.Context, in *DeleteRuntimeModelRequest, opts ...grpc.CallOption) (*DeleteRuntimeModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRuntimeModelResponse)
	err := c.cc.Invoke(ctx, Agent_DeleteRuntimeModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StreamRuntimeLogs(ctx context.Context, in *StreamRuntimeLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeLogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[1], Agent_StreamRuntimeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRuntimeLogsRequest, RuntimeLogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_StreamRuntimeLogsClient = grpc.ServerStreamingClient[RuntimeLogEntry]

func (c *agentClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, Agent_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillResponse)
	err := c.cc.Invoke(ctx, Agent_GetSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SetPermissionMode(ctx context.Context, in *SetPermissionModeRequest, opts ...grpc.CallOption) (*SetPermissionModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPermissionModeResponse)
	err := c.cc.Invoke(ctx, Agent_SetPermissionMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetPermissionMode(ctx context.Context, in *GetPermissionModeRequest, opts ...grpc.CallOption) (*GetPermissionModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionModeResponse)
	err := c.cc.Invoke(ctx, Agent_GetPermissionMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClientEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[2], Agent_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, ClientEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_SubscribeEventsClient = grpc.ServerStreamingClient[ClientEvent]

func (c *agentClient) AllowToolCall(ctx context.Context, in *AllowToolCallRequest, opts ...grpc.CallOption) (*AllowToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowToolCallResponse)
	err := c.cc.Invoke(ctx, Agent_AllowToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DenyToolCall(ctx context.Context, in *DenyToolCallRequest, opts ...grpc.CallOption) (*DenyToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyToolCallResponse)
	err := c.cc.Invoke(ctx, Agent_DenyToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetProviderCapabilities(ctx context.Context, in *GetProviderCapabilitiesRequest, opts ...grpc.CallOption) (*GetProviderCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderCapabilitiesResponse)
	err := c.cc.Invoke(ctx, Agent_GetProviderCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ProposeContextEdit(ctx context.Context, in *ProposeContextEditRequest, opts ...grpc.CallOption) (*ProposeContextEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeContextEditResponse)
	err := c.cc.Invoke(ctx, Agent_ProposeContextEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteConversationTurns(ctx context.Context, in *DeleteConversationTurnsRequest, opts ...grpc.CallOption) (*DeleteConversationTurnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationTurnsResponse)
	err := c.cc.Invoke(ctx, Agent_DeleteConversationTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListMcpServers(ctx context.Context, in *ListMcpServersRequest, opts ...grpc.CallOption) (*ListMcpServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpServersResponse)
	err := c.cc.Invoke(ctx, Agent_ListMcpServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddMcpServer(ctx context.Context, in *AddMcpServerRequest, opts ...grpc.CallOption) (*AddMcpServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMcpServerResponse)
	err := c.cc.Invoke(ctx, Agent_AddMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RemoveMcpServer(ctx context.Context, in *RemoveMcpServerRequest, opts ...grpc.CallOption) (*RemoveMcpServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMcpServerResponse)
	err := c.cc.Invoke(ctx, Agent_RemoveMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RestartMcpServer(ctx context.Context, in *RestartMcpServerRequest, opts ...grpc.CallOption) (*RestartMcpServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartMcpServerResponse)
	err := c.cc.Invoke(ctx, Agent_RestartMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetCloudProfiles(ctx context.Context, in *GetCloudProfilesRequest, opts ...grpc.CallOption) (*GetCloudProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCloudProfilesResponse)
	err := c.cc.Invoke(ctx, Agent_GetCloudProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SetActiveCloudProfile(ctx context.Context, in *SetActiveCloudProfileRequest, opts ...grpc.CallOption) (*SetActiveCloudProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveCloudProfileResponse)
	err := c.cc.Invoke(ctx, Agent_SetActiveCloudProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SetCloudProfileKey(ctx context.Context, in *SetCloudProfileKeyRequest, opts ...grpc.CallOption) (*SetCloudProfileKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCloudProfileKeyResponse)
	err := c.cc.Invoke(ctx, Agent_SetCloudProfileKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// The Agent service definition.
type AgentServer interface {
	// ProcessRequest handles AI requests (Unary).
	ProcessRequest(context.Context, *ProcessRequestRequest) (*ProcessRequestResponse, error)
	// StreamProcessRequest handles AI requests with progress updates (Streaming).
	StreamProcessRequest(*ProcessRequestRequest, grpc.ServerStreamingServer[StreamProcessResponse]) error
	// UpdateConfig updates runtime configuration (model, provider) without server restart.
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	// GetConfig returns the current runtime config. API key is reported as a
	// presence bool only — the literal value never leaves the agent.
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// Persisted-conversation surface: /history picker calls ListConversations;
	// selecting a row calls ResumeConversation; deleting a row (future) calls
	// DeleteConversation. Resume rehydrates the in-memory session store on the
	// agent so the next chat turn sees full prior context.
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	ResumeConversation(context.Context, *ResumeConversationRequest) (*ResumeConversationResponse, error)
	DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error)
	RenameConversation(context.Context, *RenameConversationRequest) (*RenameConversationResponse, error)
	GetConversation(context.Context, *GetConversationRequest) (*Conversation, error)
	// GetContextUsage reports cumulative token usage vs. the active model's
	// context window for a conversation. The CLI status bar polls this after
	// each streamed turn.
	GetContextUsage(context.Context, *GetContextUsageRequest) (*GetContextUsageResponse, error)
	// GetCompactionState returns the compaction summary + frozen/live split for
	// the /c context viewer.
	GetCompactionState(context.Context, *GetCompactionStateRequest) (*GetCompactionStateResponse, error)
	// ExportContext returns the full uncapped raw history as a JSON []llm.Message.
	ExportContext(context.Context, *ExportContextRequest) (*ExportContextResponse, error)
	// GetConversationTurns returns display-ready, side-effect-free summaries of a
	// conversation's turns for the /c context viewer. Unlike ResumeConversation
	// it does NOT re-hydrate server session state.
	GetConversationTurns(context.Context, *GetConversationTurnsRequest) (*GetConversationTurnsResponse, error)
	// ListTools enumerates the agent's registered tools (name, description,
	// permission tier). /tools in the CLI renders this through the Table
	// primitive.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// InvokeTool executes a registered tool with JSON args and returns its
	// Result. Used by /tool <name> {...args} for direct invocation; the
	// agent's chat path will dispatch tools via this same RPC once the
	// algorithmic-dispatcher lands.
	InvokeTool(context.Context, *InvokeToolRequest) (*InvokeToolResponse, error)
	// ListModels returns the models available on the active Ollama instance.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Runtime dashboard APIs expose managed runtimes, external endpoints, and
	// logs through Cercano rather than having the CLI call providers directly.
	GetRuntimeStatus(context.Context, *GetRuntimeStatusRequest) (*GetRuntimeStatusResponse, error)
	ListRuntimeModels(context.Context, *ListRuntimeModelsRequest) (*ListRuntimeModelsResponse, error)
	ListRuntimeEndpoints(context.Context, *ListRuntimeEndpointsRequest) (*ListRuntimeEndpointsResponse, error)
	StartRuntimeModel(context.Context, *StartRuntimeModelRequest) (*StartRuntimeModelResponse, error)
	StopRuntimeModel(context.Context, *StopRuntimeModelRequest) (*StopRuntimeModelResponse, error)
	RestartRuntime(context.Context, *RestartRuntimeRequest) (*RestartRuntimeResponse, error)
	DownloadRuntimeModel(context.Context, *DownloadRuntimeModelRequest) (*DownloadRuntimeModelResponse, error)
	CancelRuntimeModelDownload(context.Context, *CancelRuntimeModelDownloadRequest) (*CancelRuntimeModelDownloadResponse, error)
	DeleteRuntimeModel(context.Context, *DeleteRuntimeModelRequest) (*DeleteRuntimeModelResponse, error)
	StreamRuntimeLogs(*StreamRuntimeLogsRequest, grpc.ServerStreamingServer[RuntimeLogEntry]) error
	// ListSkills returns the catalog of available Agent Skills (name + description).
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// GetSkill returns the full SKILL.md content for a specific skill by name.
	GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error)
	// SetPermissionMode changes the agent's session permission mode.
	SetPermissionMode(context.Context, *SetPermissionModeRequest) (*SetPermissionModeResponse, error)
	// GetPermissionMode reads the current mode.
	GetPermissionMode(context.Context, *GetPermissionModeRequest) (*GetPermissionModeResponse, error)
	// SubscribeEvents is a standing server->client stream the client holds open
	// for its whole session. The agent pushes unsolicited state changes here so
	// clients never poll. First event type is PermissionModeChanged (fired when
	// the mode is changed via SetPermissionMode by any client, or when the
	// permissions file is edited out-of-band by a human or a tool).
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[ClientEvent]) error
	// AllowToolCall + DenyToolCall are how a client replies to a
	// PermissionRequired stream event.
	AllowToolCall(context.Context, *AllowToolCallRequest) (*AllowToolCallResponse, error)
	DenyToolCall(context.Context, *DenyToolCallRequest) (*DenyToolCallResponse, error)
	// GetProviderCapabilities reports what the active provider supports.
	GetProviderCapabilities(context.Context, *GetProviderCapabilitiesRequest) (*GetProviderCapabilitiesResponse, error)
	// ProposeContextEdit runs the picker model over a conversation's turn summaries
	// and returns a validated deletion proposal. Read-only — no turns are deleted.
	ProposeContextEdit(context.Context, *ProposeContextEditRequest) (*ProposeContextEditResponse, error)
	// DeleteConversationTurns hard-deletes the named turns from a conversation.
	DeleteConversationTurns(context.Context, *DeleteConversationTurnsRequest) (*DeleteConversationTurnsResponse, error)
	// ---- MCP host ----
	ListMcpServers(context.Context, *ListMcpServersRequest) (*ListMcpServersResponse, error)
	AddMcpServer(context.Context, *AddMcpServerRequest) (*AddMcpServerResponse, error)
	RemoveMcpServer(context.Context, *RemoveMcpServerRequest) (*RemoveMcpServerResponse, error)
	RestartMcpServer(context.Context, *RestartMcpServerRequest) (*RestartMcpServerResponse, error)
	// ---- Cloud profile management ----
	GetCloudProfiles(context.Context, *GetCloudProfilesRequest) (*GetCloudProfilesResponse, error)
	SetActiveCloudProfile(context.Context, *SetActiveCloudProfileRequest) (*SetActiveCloudProfileResponse, error)
	SetCloudProfileKey(context.Context, *SetCloudProfileKeyRequest) (*SetCloudProfileKeyResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) ProcessRequest(context.Context, *ProcessRequestRequest) (*ProcessRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessRequest not implemented")
}
func (UnimplementedAgentServer) StreamProcessRequest(*ProcessRequestRequest, grpc.ServerStreamingServer[StreamProcessResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessRequest not implemented")
}
func (UnimplementedAgentServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAgentServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAgentServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedAgentServer) ResumeConversation(context.Context, *ResumeConversationRequest) (*ResumeConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeConversation not implemented")
}
func (UnimplementedAgentServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedAgentServer) RenameConversation(context.Context, *RenameConversationRequest) (*RenameConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameConversation not implemented")
}
func (UnimplementedAgentServer) GetConversation(context.Context, *GetConversationRequest) (*Conversation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedAgentServer) GetContextUsage(context.Context, *GetContextUsageRequest) (*GetContextUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContextUsage not implemented")
}
func (UnimplementedAgentServer) GetCompactionState(context.Context, *GetCompactionStateRequest) (*GetCompactionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompactionState not implemented")
}
func (UnimplementedAgentServer) ExportContext(context.Context, *ExportContextRequest) (*ExportContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportContext not implemented")
}
func (UnimplementedAgentServer) GetConversationTurns(context.Context, *GetConversationTurnsRequest) (*GetConversationTurnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversationTurns not implemented")
}
func (UnimplementedAgentServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedAgentServer) InvokeTool(context.Context, *InvokeToolRequest) (*InvokeToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeTool not implemented")
}
func (UnimplementedAgentServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAgentServer) GetRuntimeStatus(context.Context, *GetRuntimeStatusRequest) (*GetRuntimeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeStatus not implemented")
}
func (UnimplementedAgentServer) ListRuntimeModels(context.Context, *ListRuntimeModelsRequest) (*ListRuntimeModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimeModels not implemented")
}
func (UnimplementedAgentServer) ListRuntimeEndpoints(context.Context, *ListRuntimeEndpointsRequest) (*ListRuntimeEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimeEndpoints not implemented")
}
func (UnimplementedAgentServer) StartRuntimeModel(context.Context, *StartRuntimeModelRequest) (*StartRuntimeModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRuntimeModel not implemented")
}
func (UnimplementedAgentServer) StopRuntimeModel(context.Context, *StopRuntimeModelRequest) (*StopRuntimeModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRuntimeModel not implemented")
}
func (UnimplementedAgentServer) RestartRuntime(context.Context, *RestartRuntimeRequest) (*RestartRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartRuntime not implemented")
}
func (UnimplementedAgentServer) DownloadRuntimeModel(context.Context, *DownloadRuntimeModelRequest) (*DownloadRuntimeModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadRuntimeModel not implemented")
}
func (UnimplementedAgentServer) CancelRuntimeModelDownload(context.Context, *CancelRuntimeModelDownloadRequest) (*CancelRuntimeModelDownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRuntimeModelDownload not implemented")
}
func (UnimplementedAgentServer) DeleteRuntimeModel(context.Context, *DeleteRuntimeModelRequest) (*DeleteRuntimeModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRuntimeModel not implemented")
}
func (UnimplementedAgentServer) StreamRuntimeLogs(*StreamRuntimeLogsRequest, grpc.ServerStreamingServer[RuntimeLogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamRuntimeLogs not implemented")
}
func (UnimplementedAgentServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAgentServer) GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedAgentServer) SetPermissionMode(context.Context, *SetPermissionModeRequest) (*SetPermissionModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPermissionMode not implemented")
}
func (UnimplementedAgentServer) GetPermissionMode(context.Context, *GetPermissionModeRequest) (*GetPermissionModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissionMode not implemented")
}
func (UnimplementedAgentServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[ClientEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedAgentServer) AllowToolCall(context.Context, *AllowToolCallRequest) (*AllowToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllowToolCall not implemented")
}
func (UnimplementedAgentServer) DenyToolCall(context.Context, *DenyToolCallRequest) (*DenyToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DenyToolCall not implemented")
}
func (UnimplementedAgentServer) GetProviderCapabilities(context.Context, *GetProviderCapabilitiesRequest) (*GetProviderCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderCapabilities not implemented")
}
func (UnimplementedAgentServer) ProposeContextEdit(context.Context, *ProposeContextEditRequest) (*ProposeContextEditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeContextEdit not implemented")
}
func (UnimplementedAgentServer) DeleteConversationTurns(context.Context, *DeleteConversationTurnsRequest) (*DeleteConversationTurnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversationTurns not implemented")
}
func (UnimplementedAgentServer) ListMcpServers(context.Context, *ListMcpServersRequest) (*ListMcpServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcpServers not implemented")
}
func (UnimplementedAgentServer) AddMcpServer(context.Context, *AddMcpServerRequest) (*AddMcpServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMcpServer not implemented")
}
func (UnimplementedAgentServer) RemoveMcpServer(context.Context, *RemoveMcpServerRequest) (*RemoveMcpServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMcpServer not implemented")
}
func (UnimplementedAgentServer) RestartMcpServer(context.Context, *RestartMcpServerRequest) (*RestartMcpServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartMcpServer not implemented")
}
func (UnimplementedAgentServer) GetCloudProfiles(context.Context, *GetCloudProfilesRequest) (*GetCloudProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloudProfiles not implemented")
}
func (UnimplementedAgentServer) SetActiveCloudProfile(context.Context, *SetActiveCloudProfileRequest) (*SetActiveCloudProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveCloudProfile not implemented")
}
func (UnimplementedAgentServer) SetCloudProfileKey(context.Context, *SetCloudProfileKeyRequest) (*SetCloudProfileKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCloudProfileKey not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_ProcessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ProcessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ProcessRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ProcessRequest(ctx, req.(*ProcessRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StreamProcessRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessRequestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).StreamProcessRequest(m, &grpc.GenericServerStream[ProcessRequestRequest, StreamProcessResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_StreamProcessRequestServer = grpc.ServerStreamingServer[StreamProcessResponse]

func _Agent_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ResumeConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ResumeConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ResumeConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ResumeConversation(ctx, req.(*ResumeConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RenameConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RenameConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RenameConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RenameConversation(ctx, req.(*RenameConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetContextUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetContextUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetContextUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetContextUsage(ctx, req.(*GetContextUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetCompactionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompactionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetCompactionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetCompactionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetCompactionState(ctx, req.(*GetCompactionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ExportContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ExportContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ExportContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ExportContext(ctx, req.(*ExportContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetConversationTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationTurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetConversationTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetConversationTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetConversationTurns(ctx, req.(*GetConversationTurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_InvokeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).InvokeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_InvokeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).InvokeTool(ctx, req.(*InvokeToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetRuntimeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetRuntimeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetRuntimeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetRuntimeStatus(ctx, req.(*GetRuntimeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListRuntimeModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimeModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListRuntimeModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListRuntimeModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListRuntimeModels(ctx, req.(*ListRuntimeModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListRuntimeEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimeEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListRuntimeEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListRuntimeEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListRuntimeEndpoints(ctx, req.(*ListRuntimeEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StartRuntimeModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRuntimeModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StartRuntimeModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StartRuntimeModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StartRuntimeModel(ctx, req.(*StartRuntimeModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopRuntimeModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRuntimeModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopRuntimeModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StopRuntimeModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopRuntimeModel(ctx, req.(*StopRuntimeModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RestartRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RestartRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RestartRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RestartRuntime(ctx, req.(*RestartRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DownloadRuntimeModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRuntimeModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DownloadRuntimeModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DownloadRuntimeModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DownloadRuntimeModel(ctx, req.(*DownloadRuntimeModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CancelRuntimeModelDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRuntimeModelDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CancelRuntimeModelDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CancelRuntimeModelDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CancelRuntimeModelDownload(ctx, req.(*CancelRuntimeModelDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteRuntimeModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuntimeModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteRuntimeModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteRuntimeModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteRuntimeModel(ctx, req.(*DeleteRuntimeModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StreamRuntimeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRuntimeLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).StreamRuntimeLogs(m, &grpc.GenericServerStream[StreamRuntimeLogsRequest, RuntimeLogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_StreamRuntimeLogsServer = grpc.ServerStreamingServer[RuntimeLogEntry]

func _Agent_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetSkill(ctx, req.(*GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SetPermissionMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPermissionModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SetPermissionMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SetPermissionMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SetPermissionMode(ctx, req.(*SetPermissionModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetPermissionMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetPermissionMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetPermissionMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetPermissionMode(ctx, req.(*GetPermissionModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, ClientEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_SubscribeEventsServer = grpc.ServerStreamingServer[ClientEvent]

func _Agent_AllowToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AllowToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_AllowToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AllowToolCall(ctx, req.(*AllowToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DenyToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DenyToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DenyToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DenyToolCall(ctx, req.(*DenyToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetProviderCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetProviderCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetProviderCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetProviderCapabilities(ctx, req.(*GetProviderCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ProposeContextEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeContextEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ProposeContextEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ProposeContextEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ProposeContextEdit(ctx, req.(*ProposeContextEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteConversationTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationTurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteConversationTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteConversationTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteConversationTurns(ctx, req.(*DeleteConversationTurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListMcpServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListMcpServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListMcpServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListMcpServers(ctx, req.(*ListMcpServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMcpServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_AddMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddMcpServer(ctx, req.(*AddMcpServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RemoveMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMcpServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RemoveMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RemoveMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RemoveMcpServer(ctx, req.(*RemoveMcpServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RestartMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartMcpServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RestartMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RestartMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RestartMcpServer(ctx, req.(*RestartMcpServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetCloudProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloudProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetCloudProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetCloudProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetCloudProfiles(ctx, req.(*GetCloudProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SetActiveCloudProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveCloudProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SetActiveCloudProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SetActiveCloudProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SetActiveCloudProfile(ctx, req.(*SetActiveCloudProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SetCloudProfileKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCloudProfileKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SetCloudProfileKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SetCloudProfileKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SetCloudProfileKey(ctx, req.(*SetCloudProfileKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRequest",
			Handler:    _Agent_ProcessRequest_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _Agent_UpdateConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Agent_GetConfig_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _Agent_ListConversations_Handler,
		},
		{
			MethodName: "ResumeConversation",
			Handler:    _Agent_ResumeConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _Agent_DeleteConversation_Handler,
		},
		{
			MethodName: "RenameConversation",
			Handler:    _Agent_RenameConversation_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _Agent_GetConversation_Handler,
		},
		{
			MethodName: "GetContextUsage",
			Handler:    _Agent_GetContextUsage_Handler,
		},
		{
			MethodName: "GetCompactionState",
			Handler:    _Agent_GetCompactionState_Handler,
		},
		{
			MethodName: "ExportContext",
			Handler:    _Agent_ExportContext_Handler,
		},
		{
			MethodName: "GetConversationTurns",
			Handler:    _Agent_GetConversationTurns_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _Agent_ListTools_Handler,
		},
		{
			MethodName: "InvokeTool",
			Handler:    _Agent_InvokeTool_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Agent_ListModels_Handler,
		},
		{
			MethodName: "GetRuntimeStatus",
			Handler:    _Agent_GetRuntimeStatus_Handler,
		},
		{
			MethodName: "ListRuntimeModels",
			Handler:    _Agent_ListRuntimeModels_Handler,
		},
		{
			MethodName: "ListRuntimeEndpoints",
			Handler:    _Agent_ListRuntimeEndpoints_Handler,
		},
		{
			MethodName: "StartRuntimeModel",
			Handler:    _Agent_StartRuntimeModel_Handler,
		},
		{
			MethodName: "StopRuntimeModel",
			Handler:    _Agent_StopRuntimeModel_Handler,
		},
		{
			MethodName: "RestartRuntime",
			Handler:    _Agent_RestartRuntime_Handler,
		},
		{
			MethodName: "DownloadRuntimeModel",
			Handler:    _Agent_DownloadRuntimeModel_Handler,
		},
		{
			MethodName: "CancelRuntimeModelDownload",
			Handler:    _Agent_CancelRuntimeModelDownload_Handler,
		},
		{
			MethodName: "DeleteRuntimeModel",
			Handler:    _Agent_DeleteRuntimeModel_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _Agent_ListSkills_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _Agent_GetSkill_Handler,
		},
		{
			MethodName: "SetPermissionMode",
			Handler:    _Agent_SetPermissionMode_Handler,
		},
		{
			MethodName: "GetPermissionMode",
			Handler:    _Agent_GetPermissionMode_Handler,
		},
		{
			MethodName: "AllowToolCall",
			Handler:    _Agent_AllowToolCall_Handler,
		},
		{
			MethodName: "DenyToolCall",
			Handler:    _Agent_DenyToolCall_Handler,
		},
		{
			MethodName: "GetProviderCapabilities",
			Handler:    _Agent_GetProviderCapabilities_Handler,
		},
		{
			MethodName: "ProposeContextEdit",
			Handler:    _Agent_ProposeContextEdit_Handler,
		},
		{
			MethodName: "DeleteConversationTurns",
			Handler:    _Agent_DeleteConversationTurns_Handler,
		},
		{
			MethodName: "ListMcpServers",
			Handler:    _Agent_ListMcpServers_Handler,
		},
		{
			MethodName: "AddMcpServer",
			Handler:    _Agent_AddMcpServer_Handler,
		},
		{
			MethodName: "RemoveMcpServer",
			Handler:    _Agent_RemoveMcpServer_Handler,
		},
		{
			MethodName: "RestartMcpServer",
			Handler:    _Agent_RestartMcpServer_Handler,
		},
		{
			MethodName: "GetCloudProfiles",
			Handler:    _Agent_GetCloudProfiles_Handler,
		},
		{
			MethodName: "SetActiveCloudProfile",
			Handler:    _Agent_SetActiveCloudProfile_Handler,
		},
		{
			MethodName: "SetCloudProfileKey",
			Handler:    _Agent_SetCloudProfileKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProcessRequest",
			Handler:       _Agent_StreamProcessRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRuntimeLogs",
			Handler:       _Agent_StreamRuntimeLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _Agent_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "source/proto/agent.proto",
}
